dtbo-$(CONFIG_ARCH_STM32) += \
	stm-fire-bluetooth.dtbo \
	stm-fire-led.dtbo \
	stm-fire-key.dtbo \
	stm-fire-i2c1.dtbo \
	stm-fire-i2c2.dtbo \
	stm-fire-lcd.dtbo \
	stm-fire-cam.dtbo \
	stm-fire-touch-capacitive-goodix.dtbo \
	stm-fire-can.dtbo \
	stm-fire-hdmi.dtbo \
	stm-fire-sound.dtbo \
	stm-fire-btwifi.dtbo \
	stm-fire-adc.dtbo \
	stm-fire-mipi.dtbo \
	stm-fire-usart1.dtbo \
	stm-fire-usart3.dtbo \
	stm-fire-mpu6050.dtbo \
	stm-fire-485r1.dtbo \
	stm-fire-485r2.dtbo \
	stm-fire-spi4.dtbo \
	stm-fire-ltdc.dtbo \
	stm-fire-touch-capacitive-4.3.dtbo

targets += dtbs dtbs_install
targets += $(dtbo-y)

always		:= $(dtbo-y)
clean-files	:= *.dtbo
